# .github/workflows/publish.yml
name: Build and Publish

on:
  push:
    branches:
      - master
      - develop

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      # Keep id-token write permission if you plan to use OIDC/trusted publishing later.
      # Remove if only API tokens will be used.
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Use a specific version for consistency
      - name: Set up uv
        uses: astral-sh/setup-uv@v1
      # - name: Install uv # Removed manual installation
      #   run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: uv sync --system --dev # Need dev deps for tests
      - name: Run tests # Ensure tests pass before publishing
        run: uv run pytest
      - name: Build package
        run: uv build --sdist --wheel -o dist/ .

      # Publish to TestPyPI for 'develop' branch
      - name: Publish package to TestPyPI
        if: github.ref == 'refs/heads/develop'
        run: >
          uv publish --repository-url https://test.pypi.org/legacy/
          -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }} dist/*

      # Publish to PyPI for 'master' branch
      - name: Publish package to PyPI
        if: github.ref == 'refs/heads/master'
        run: >
          uv publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*
